#############################################################################
# Makefile for building: Echecs
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Echecs.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Echecs.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Echecs1.0.0
DISTDIR = /home/loic/Documents/workspace/Echecs/.tmp/Echecs1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Cavalier.cpp \
		src/Echiquier.cpp \
		src/FactoryPiece.cpp \
		src/Fenetre.cpp \
		src/Fou.cpp \
		src/Joueur.cpp \
		src/Main.cpp \
		src/Mouvement.cpp \
		src/MouvementCavalier.cpp \
		src/MouvementDiagonale.cpp \
		src/MouvementHorizontal.cpp \
		src/MouvementPion.cpp \
		src/MouvementRoque.cpp \
		src/MouvementVertical.cpp \
		src/Partie.cpp \
		src/Piece.cpp \
		src/Pion.cpp \
		src/Reine.cpp \
		src/Roi.cpp \
		src/Tour.cpp moc_Fenetre.cpp
OBJECTS       = Cavalier.o \
		Echiquier.o \
		FactoryPiece.o \
		Fenetre.o \
		Fou.o \
		Joueur.o \
		Main.o \
		Mouvement.o \
		MouvementCavalier.o \
		MouvementDiagonale.o \
		MouvementHorizontal.o \
		MouvementPion.o \
		MouvementRoque.o \
		MouvementVertical.o \
		Partie.o \
		Piece.o \
		Pion.o \
		Reine.o \
		Roi.o \
		Tour.o \
		moc_Fenetre.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Echecs.pro src/Cavalier.hpp \
		src/Colormod.hpp \
		src/Echiquier.hpp \
		src/FactoryPiece.hpp \
		src/Fenetre.hpp \
		src/Fou.hpp \
		src/Joueur.hpp \
		src/Mouvement.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp \
		src/MouvementVertical.hpp \
		src/Partie.hpp \
		src/Piece.hpp \
		src/Pion.hpp \
		src/Reine.hpp \
		src/Roi.hpp \
		src/Tour.hpp \
		src/utils.hpp src/Cavalier.cpp \
		src/Echiquier.cpp \
		src/FactoryPiece.cpp \
		src/Fenetre.cpp \
		src/Fou.cpp \
		src/Joueur.cpp \
		src/Main.cpp \
		src/Mouvement.cpp \
		src/MouvementCavalier.cpp \
		src/MouvementDiagonale.cpp \
		src/MouvementHorizontal.cpp \
		src/MouvementPion.cpp \
		src/MouvementRoque.cpp \
		src/MouvementVertical.cpp \
		src/Partie.cpp \
		src/Piece.cpp \
		src/Pion.cpp \
		src/Reine.cpp \
		src/Roi.cpp \
		src/Tour.cpp
QMAKE_TARGET  = Echecs
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Echecs


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Echecs.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Echecs.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Echecs.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Echecs.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Echecs.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/Cavalier.hpp src/Colormod.hpp src/Echiquier.hpp src/FactoryPiece.hpp src/Fenetre.hpp src/Fou.hpp src/Joueur.hpp src/Mouvement.hpp src/MouvementCavalier.hpp src/MouvementDiagonale.hpp src/MouvementHorizontal.hpp src/MouvementPion.hpp src/MouvementRoque.hpp src/MouvementVertical.hpp src/Partie.hpp src/Piece.hpp src/Pion.hpp src/Reine.hpp src/Roi.hpp src/Tour.hpp src/utils.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Cavalier.cpp src/Echiquier.cpp src/FactoryPiece.cpp src/Fenetre.cpp src/Fou.cpp src/Joueur.cpp src/Main.cpp src/Mouvement.cpp src/MouvementCavalier.cpp src/MouvementDiagonale.cpp src/MouvementHorizontal.cpp src/MouvementPion.cpp src/MouvementRoque.cpp src/MouvementVertical.cpp src/Partie.cpp src/Piece.cpp src/Pion.cpp src/Reine.cpp src/Roi.cpp src/Tour.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Fenetre.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Fenetre.cpp
moc_Fenetre.cpp: src/Fenetre.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/loic/Documents/workspace/Echecs -I/home/loic/Documents/workspace/Echecs -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Fenetre.hpp -o moc_Fenetre.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Cavalier.o: src/Cavalier.cpp src/Cavalier.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cavalier.o src/Cavalier.cpp

Echiquier.o: src/Echiquier.cpp src/Echiquier.hpp \
		src/Colormod.hpp \
		src/utils.hpp \
		src/FactoryPiece.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp \
		src/Roi.hpp \
		src/Reine.hpp \
		src/Fou.hpp \
		src/Cavalier.hpp \
		src/Tour.hpp \
		src/Pion.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Echiquier.o src/Echiquier.cpp

FactoryPiece.o: src/FactoryPiece.cpp src/FactoryPiece.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp \
		src/Roi.hpp \
		src/Reine.hpp \
		src/Fou.hpp \
		src/Cavalier.hpp \
		src/Tour.hpp \
		src/Pion.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FactoryPiece.o src/FactoryPiece.cpp

Fenetre.o: src/Fenetre.cpp src/Fenetre.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fenetre.o src/Fenetre.cpp

Fou.o: src/Fou.cpp src/Fou.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fou.o src/Fou.cpp

Joueur.o: src/Joueur.cpp src/Joueur.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Joueur.o src/Joueur.cpp

Main.o: src/Main.cpp src/Fenetre.hpp \
		src/Partie.hpp \
		src/utils.hpp \
		src/Joueur.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o src/Main.cpp

Mouvement.o: src/Mouvement.cpp src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mouvement.o src/Mouvement.cpp

MouvementCavalier.o: src/MouvementCavalier.cpp src/MouvementCavalier.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementCavalier.o src/MouvementCavalier.cpp

MouvementDiagonale.o: src/MouvementDiagonale.cpp src/MouvementDiagonale.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementDiagonale.o src/MouvementDiagonale.cpp

MouvementHorizontal.o: src/MouvementHorizontal.cpp src/MouvementHorizontal.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementHorizontal.o src/MouvementHorizontal.cpp

MouvementPion.o: src/MouvementPion.cpp src/MouvementPion.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementPion.o src/MouvementPion.cpp

MouvementRoque.o: src/MouvementRoque.cpp src/MouvementRoque.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementRoque.o src/MouvementRoque.cpp

MouvementVertical.o: src/MouvementVertical.cpp src/MouvementVertical.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MouvementVertical.o src/MouvementVertical.cpp

Partie.o: src/Partie.cpp src/Partie.hpp \
		src/utils.hpp \
		src/Joueur.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Partie.o src/Partie.cpp

Piece.o: src/Piece.cpp src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Piece.o src/Piece.cpp

Pion.o: src/Pion.cpp src/Pion.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pion.o src/Pion.cpp

Reine.o: src/Reine.cpp src/Reine.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Reine.o src/Reine.cpp

Roi.o: src/Roi.cpp src/Roi.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Roi.o src/Roi.cpp

Tour.o: src/Tour.cpp src/Tour.hpp \
		src/Piece.hpp \
		src/Mouvement.hpp \
		src/utils.hpp \
		src/Echiquier.hpp \
		src/Colormod.hpp \
		src/MouvementHorizontal.hpp \
		src/MouvementVertical.hpp \
		src/MouvementDiagonale.hpp \
		src/MouvementCavalier.hpp \
		src/MouvementPion.hpp \
		src/MouvementRoque.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tour.o src/Tour.cpp

moc_Fenetre.o: moc_Fenetre.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Fenetre.o moc_Fenetre.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

